### ISSUE TITLE
Emit `revoked` so users won't need to observe relation_departed

### ISSUE THREAD

**Issue by sed-i** [PietroPasotti/traefik-route-k8s-operator#21]
Currently, `traefik_route` only emits `ready`

https://github.com/canonical/traefik-route-k8s-operator/blob/55313c628d13f601f2f463b807d51229979c7723/lib/charms/traefik_route_k8s/v0/traefik_route.py#L185-L189

IPU and IPA also emit `revoked`
- https://github.com/canonical/traefik-k8s-operator/blob/61bc8ba788bb380300a8ab651df749a3644ae947/lib/charms/traefik_k8s/v1/ingress.py#L280
- https://github.com/canonical/traefik-k8s-operator/blob/61bc8ba788bb380300a8ab651df749a3644ae947/lib/charms/traefik_k8s/v1/ingress_per_unit.py#L729

It could be handy to have a revoked here as well so users could only observe `self.ingress.revoked`.

**Comment by dstathis** [comment]
Closing as this has been open for 2 years. Feel free to reopen in the traefik repo if needed.
