### ISSUE TITLE
support path-only root url 

### ISSUE THREAD

**Issue by PietroPasotti** [PietroPasotti/traefik-route-k8s-operator#3]
If the root_url begins with `/`, we will fill in the host and port for you: 

root_url="/baz/" will become: `http://{external-hostname | loadbalancer ip}:{port}/baz/`

This requires passing the host and port data from traefik to traefik-route, or passing the url template from Route to Traefik and the rendered url back to Route. (I guess the first is fine).

**Comment by dstathis** [comment]
Stale. Feel free to reopen in the Traefik repo.
