### ISSUE TITLE
Should this charm be archived?

### ISSUE THREAD

**Issue by mmkay** [PietroPasotti/traefik-route-k8s-operator#55]
- it looks like the charm isn't actively used by the community.
- it contains a library that is used heavily (`traefik_route_k8s` but in combination with traefik-k8s-operator so it might be a better place to own this library - ref canonical/traefik-k8s-operator#379 )

It looks like we should consider archiving this charm and moving `traefik_route_k8s` library to traefik-k8s-operator.

**Comment by dstathis** [comment]
On it.
