### ISSUE TITLE
Libpatch 10 of the traefik_route library isn't published

### ISSUE THREAD

**Issue by arturo-seijas** [PietroPasotti/traefik-route-k8s-operator#58]
### Bug Description

Hi!
I've noticed [tempo is using revision 10 of the traefik_route library](https://github.com/canonical/tempo-coordinator-k8s-operator/blob/main/lib/charms/traefik_route_k8s/v0/traefik_route.py#L91), but that revision is [not published in charmhub](https://charmhub.io/traefik-route-k8s/libraries/traefik_route/source-code).
Can you please release it?

### To Reproduce

`juju fetch-lib charms.traefik_route_k8s.v0.traefik_route`

### Environment

Any

### Relevant log output

```shell
None
```

**Comment by mmkay** [comment]
This is likely related to https://github.com/canonical/traefik-k8s-operator/issues/379.
